/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_extremesolution_nilefm_media_AACPlayer */

#ifndef _Included_org_extremesolution_nilefm_media_AACPlayer
#define _Included_org_extremesolution_nilefm_media_AACPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_extremesolution_nilefm_media_AACPlayer_AAC_BUFFER_SIZE
#define org_extremesolution_nilefm_media_AACPlayer_AAC_BUFFER_SIZE 10240L
/*
 * Class:     org_extremesolution_nilefm_media_AACPlayer
 * Method:    initNative
 * Signature: (Lorg/extremesolution/nilefm/media/AACPlayer;[BI)Lorg/extremesolution/nilefm/media/AACInfo;
 */
JNIEXPORT jobject JNICALL Java_org_extremesolution_nilefm_media_AACPlayer_initNative
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     org_extremesolution_nilefm_media_AACPlayer
 * Method:    decodeNative
 * Signature: (Lorg/extremesolution/nilefm/media/AACPlayer;[BI)Lorg/extremesolution/nilefm/media/DecodingInfo;
 */
JNIEXPORT jobject JNICALL Java_org_extremesolution_nilefm_media_AACPlayer_decodeNative
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     org_extremesolution_nilefm_media_AACPlayer
 * Method:    releaseNative
 * Signature: (Lorg/extremesolution/nilefm/media/AACPlayer;)V
 */
JNIEXPORT void JNICALL Java_org_extremesolution_nilefm_media_AACPlayer_releaseNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
