/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jvshahid_mediaplayer_AACPlayer */

#ifndef _Included_com_github_jvshahid_mediaplayer_AACPlayer
#define _Included_com_github_jvshahid_mediaplayer_AACPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_jvshahid_mediaplayer_AACPlayer_AAC_BUFFER_SIZE
#define com_github_jvshahid_mediaplayer_AACPlayer_AAC_BUFFER_SIZE 10240L
/*
 * Class:     com_github_jvshahid_mediaplayer_AACPlayer
 * Method:    initNative
 * Signature: (Lcom/github/jvshahid/mediaplayer/AACPlayer;[BI)Lcom/github/jvshahid/mediaplayer/AACInfo;
 */
JNIEXPORT jobject JNICALL Java_com_github_jvshahid_mediaplayer_AACPlayer_initNative
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     com_github_jvshahid_mediaplayer_AACPlayer
 * Method:    decodeNative
 * Signature: (Lcom/github/jvshahid/mediaplayer/AACPlayer;[BI)Lcom/github/jvshahid/mediaplayer/DecodingInfo;
 */
JNIEXPORT jobject JNICALL Java_com_github_jvshahid_mediaplayer_AACPlayer_decodeNative
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     com_github_jvshahid_mediaplayer_AACPlayer
 * Method:    releaseNative
 * Signature: (Lcom/github/jvshahid/mediaplayer/AACPlayer;)V
 */
JNIEXPORT void JNICALL Java_com_github_jvshahid_mediaplayer_AACPlayer_releaseNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
